export const products = [
  {
    name: "EUROLINE 810 POP UP 700 W Pop Up Toaster  (White)",
    productId: "EURO19938201",
    brandName: "EUROLINE",
    category: "Pop Up Toasters",
    companyAssured: false,
    rating: "4.2",
    price: "12232",
    discount: "50%",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/k5lcvbk0/pop-up-toaster/2/j/w/euroline-820-pop-up-810-pop-up-original-imafz8h3duveqgh7.jpeg?q=70",
    sellerName: "telform inc.",
    isNewProduct: true,
  },
  {
    name: "Morphy Richards 25 L Convection Microwave Oven  (MWO 25CG, Steel)",
    productId: "EURO19938202",
    brandName: "Morphy",
    category: "Microwave Ovens",
    companyAssured: true,
    rating: "3.9",
    price: "10999",
    discount: "11%",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/microwave-new/v/q/y/morphy-richard-25cg-original-imaec2ddymudmze3.jpeg?q=70",
    sellerName: "Kwitch Retails",
    isNewProduct: false,
  },
  {
    name: "Fitbit Inspire 2  (Desert Rose Strap, Size : Regular)",
    productId: "EURO19938203",
    brandName: "Fitbit",
    category: "Smart Bands",
    companyAssured: true,
    rating: "3.9",
    price: "17992",
    discount: "12%",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/khmbafk0/smart-band-tag/u/z/6/no-yes-fb418bkcr-android-ios-fitbit-yes-original-imafxhe4ff7ys5bc.jpeg?q=70",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "Crystal Furnitech Vienna Engineered Wood Cupboard",
    productId: "EURO19938204",
    brandName: "Crystal Furnitech",
    category: "Furniture",
    companyAssured: true,
    rating: "3.9",
    price: "8390",
    discount: "12%",
    imageURL:
      "https://rukminim2.flixcart.com/image/612/612/kh5607k0-0/cupboard-almirah/6/n/b/particle-board-csi-72a-crystal-furnitech-wenge-original-imafx7vjxy6vsygj.jpeg?q=70",
    sellerName: "OmniTechRetail",
    isNewProduct: true,
  },
  {
    name: "MUSCLEBLAZE Creatine Monohydrate Creatine  (100 g, Unflavored)",
    productId: "EURO19938205",
    brandName: "MUSCLEBLAZE",
    category: "Nutrition",
    companyAssured: true,
    rating: "4.2",
    price: "419",
    discount: "16%",
    imageURL:
      "https://rukminim2.flixcart.com/image/416/416/jxkpx8w0/protein-supplement/x/r/n/creatine-monohydrate-nut1369-03-muscleblaze-original-imafgye5w752wj4w.jpeg?q=70",
    sellerName: "BrightLifecare",
    isNewProduct: true,
  },
  {
    name: "SAMSUNG 80 cm (32 inch) HD Ready LED Smart TV  (UA32T4340AKXXL / UA32T4340BKXXL)",
    productId: "EURO19938206",
    brandName: "Samsung",
    category: "TV",
    companyAssured: true,
    rating: "4.4",
    price: "16990",
    discount: "26%",
    imageURL:
      "https://rukminim2.flixcart.com/image/416/416/kbs9k7k0/television/c/j/3/samsung-ua32t4340akxxl-original-imaft25qdysfsq7k.jpeg?q=70",
    sellerName: "OmniTechRetail",
    isNewProduct: true,
  },
  {
    name: "Questions are the Answers  (English, Paperback, Pease Allan)",
    productId: "EURO19938207",
    brandName: "Please Allan",
    category: "Books",
    companyAssured: true,
    rating: "",
    price: "117",
    discount: "22%",
    imageURL:
      "https://rukminim2.flixcart.com/image/416/416/book/0/5/9/questions-are-the-answers-original-imadsqgtwqpbmbaz.jpeg?q=70",
    sellerName: "TrueComRetail",
    isNewProduct: true,
  },
  {
    name: "Printed Men Hooded Neck Dark Green, Black T-Shirt",
    productId: "EURO19938208",
    brandName: "BLIVE",
    category: "Clothing",
    companyAssured: true,
    rating: "4",
    price: "139",
    discount: "90%",
    imageURL:
      "https://rukminim2.flixcart.com/image/800/960/kixgtjk0-0/t-shirt/h/u/4/s-bogrblhdful-z15-blive-original-imafyhv6qgdhmvzc.jpeg?q=50",
    sellerName: "TRIPR",
    isNewProduct: true,
  },
  {
    name: "NXI Exceed Helicopter Sensor Aircraft 2 in 1 Flying Helicopter with Remote  (Multicolor)",
    productId: "EURO19938209",
    brandName: "NXI",
    category: "Toys",
    companyAssured: true,
    rating: "3.4",
    price: "460",
    discount: "49%",
    imageURL:
      "https://rukminim2.flixcart.com/image/416/416/kksmikw0/remote-control-toy/0/p/f/intelligent-flying-outdoor-induction-helicopter-with-remote-original-imagy29dvzvmu4rm.jpeg?q=70",
    sellerName: "PicChu",
    isNewProduct: true,
  },
  {
    name: "Learning How To Fly - Life Lessons for the Youth  (English, Paperback, Kalam Abdul A. P. J.)",
    productId: "EURO19938210",
    brandName: "APJ Abdul Kalam",
    category: "Books",
    companyAssured: true,
    rating: "4.6",
    price: "195",
    discount: "5%",
    imageURL:
      "https://rukminim2.flixcart.com/image/416/416/kjbr8280-0/book/z/r/9/learning-how-to-fly-original-imafyx6zuhvfhv94.jpeg?q=70",
    sellerName: "Repro Books on Demand",
    isNewProduct: true,
  },
];
